### ISSUE TITLE
UTS2_2.4.0 could not find depth information(URP)

### ISSUE THREAD

**Issue by RuyeRuye** [unity3d-jp/UnityChanToonShaderVer2_Project#100]
Unity:2021.2
I use this shader on the model. The model is simply ignored when the depth information of the camera is obtained, which causes the simulated volumetric light to pass through the model and the model to be hidden when the depth image is displayed. Impression version 2.3.0 and unity2020.3 do not have this issue.
<img width="1010" alt="depth" src="https://user-images.githubusercontent.com/88803076/153387739-e2fb9902-3a9b-4da9-9a03-139b4fb402ef.png">
<img width="772" alt="scene" src="https://user-images.githubusercontent.com/88803076/153387759-0f8d06d9-630f-4f12-aed6-2c230909dd07.png">

**Comment by H3idi-X** [comment]
Hi, Thanks for the report. We'll look into that.

**Comment by H3idi-X** [comment]
Hi, will you please explain specific process to reproduce the issue  like submitting bug reports with Unity bug reporter? 

Adding a example project would help a lot. 

1. What happened
2. How can we reproduce it .

**Comment by H3idi-X** [comment]
Hi, we have just released [2.5.0 ](https://github.com/unity3d-jp/UnityChanToonShaderVer2_Project/releases/tag/urp-2.5.0) adapting the patch above. Will you please check that one?
Thanks.
