### ISSUE TITLE
透過ウィンドウに表示したときに、ウィンドウの後ろ側が透けて見えてしまう

### ISSUE THREAD

**Issue by TP-113** [unity3d-jp/UnityChanToonShaderVer2_Project#102]
こんにちは。

現在、UnityのWindowsStandaloneビルドで透過ウィンドウを使用し、3Dモデルのキャラクターをデスクトップマスコットのように表示させるアプリを作っています。UnityChanToonShader v2.0.8を使用させていただいているのですが、半透明表示の部分の描画に問題が発生しています。

キャラの前髪が半透明になるようにUnityChanToonShader/Toon_ShadingGradeMap_TransClippingを使用して、テクスチャの半透明部分が反映されるように設定しています。エディタ上で実行したときは正常に表示されるのですが、ビルドして透過ウィンドウ上に表示したときはウィンドウの後ろにある物が半透明部分を通して見えてしまいます。

ユニティちゃんの前髪へ適当に半透明マテリアルを設定してyahooトップ画面の上に透過ウィンドウを表示したときの様子を添付します。このように、前髪の後ろにおでこがあるはずの部分まで後ろのyahooの画面が透けてしまっています。

![image](https://user-images.githubusercontent.com/30720776/154395475-3749dc17-89ab-4964-836f-3f8443e14da1.png)

透過ウィンドウ上でもキャラの半透明部分が正しく表示されるようにしたいのですが、何か方法はありませんでしょうか？よろしくお願いします。

ちなみに、透過ウィンドウにするために使用しているライブラリはKirurobo氏のこちらのリポジトリになります。→https://github.com/kirurobo/UniWindowController

**Comment by H3idi-X** [comment]
こんにちは。UnityChanToonShader をお使いいただきありがとうございます。
恐れ入りますが、Unity をフックして動作しているモジュールで発生する問題は　Unityや UnityChanToonShader の Issue として扱うのは無理があります。本件はクローズとさせていただきます。
