### ISSUE TITLE
Depth Priming Mode

### ISSUE THREAD

**Issue by omoto-fivefor** [unity3d-jp/UnityChanToonShaderVer2_Project#104]
Outline is not displayed when using Depth Priming Mode in URP12.

The version of UTS/UniversalToon you are using :e.g. UTS/UniversalToon v.2.5.0
The version of Unity you are using :e.g. Unity 2021.2.7f1
Type of OS using Unity :e.g. Windows 11
The version of Universal RP you are using :e.g. Version 12.1.2

**Comment by H3idi-X** [comment]
Hi, Thanks for reporting the issue. we confirmed that occurs. We will check whether we can support outline in Depth Priming Mode.  

![image](https://user-images.githubusercontent.com/4477357/159855555-6c37293d-c190-4d57-b567-9e46d8dcf586.png)

**Comment by H3idi-X** [comment]
Oh, sorry. What I have said was wrong. It must be happening only in SceneViews, not in GameViews, which is by design when using Depth Priming Mode. Will you please check again? 

![image](https://user-images.githubusercontent.com/4477357/159879773-321a847b-de7b-4ab1-82e6-fb5c9c1a0e89.png)

**Comment by omoto-fivefor** [comment]
Thank you for your advice.
I found that the outline is not displayed when Depth Priming Mode is enforced and the outline is not displayed when the game view gizmo is enabled.
