### ISSUE TITLE
HDRP and LWRP support?

### ISSUE THREAD

**Issue by optimisez** [unity3d-jp/UnityChanToonShaderVer2_Project#11]
Any plan to support HDRP (High-Definition Rendering Pipeline) and LWRP (Lightweight Rendering Pipeline) in future updates?

**Comment by phields** [comment]
@Nobuyuki-Kobayashi

**Comment by Nobuyuki-Kobayashi** [comment]
We/UTJ have the plan to do so, but the precise schedule is undecided now.
