### ISSUE TITLE
Unity Chan in URP?

### ISSUE THREAD

**Issue by Mashimaro7** [unity3d-jp/UnityChanToonShaderVer2_Project#111]
I've been looking around the documentation for awhile and I can't find anything on this, how do I get it to work in URP? The old version had a separate project specifically for URP, but I can't find any shaders or examples for URP? My project is in URP and I need it for some other shaders, so it would be great if i could use this in URP.

Thanks

**Comment by H3idi-X** [comment]
Hi, as for shader, have you checked [this branch](https://github.com/unity3d-jp/UnityChanToonShaderVer2_Project/tree/release/urp/2.5.1)? 
And a sample is [here](https://github.com/unity3d-jp/UnityChanSSU/releases).

**Comment by Thaina** [comment]
Could we have latest branch become default branch of this project? Since it not default people would confuse that the main branch they came to see first haven't been updated and make it felt like this repo was not maintained anymore

**Comment by H3idi-X** [comment]
Hi, we are in transition to[ Unity Toon Shader](https://github.com/Unity-Technologies/com.unity.toonshader) which is compatible with all the render pipeline. All the feature Unity-chan Toon shader has is implemented to the one too. Will you please check that new shader?

**Comment by Thaina** [comment]
I see. Thank you very much

**Comment by Thaina** [comment]
@H3idi-X This still cause same issue in this package I mention in https://github.com/unity3d-jp/UnityChanToonShaderVer2_Project/issues/118

This package use the oldest format, it still in `UnityChan` folder. Which could not be convert by converter

Could you please upgrade this package or made converter in [com.unity.toonshader](https://github.com/Unity-Technologies/com.unity.toonshader) or have some manual to upgrade it to latest version?

![image](https://user-images.githubusercontent.com/1042507/205553563-583748e2-650d-4ffa-9949-5a8ee2659af3.png) ![image](https://user-images.githubusercontent.com/1042507/205553584-adc17e4a-cd9f-4108-831d-499a51c80f73.png)
