### ISSUE TITLE
Shadows between model data do not fall.

### ISSUE THREAD

**Issue by kumi0708** [unity3d-jp/UnityChanToonShaderVer2_Project#112]
Hello.

I am working on a UnityChanToonShaderVer2_Project.

When I create a work, the shadows between the model data do not fall.
Is this a specification?

Also, I would like to know if there is another way to get shadows between model data.
I would like to know if there is another way to get the shadows between the model data.

**Comment by H3idi-X** [comment]
Hi, Have you enabled **Receive System Shadows** option? 


![image](https://user-images.githubusercontent.com/4477357/187828041-557516a5-459e-42b0-8701-fdd791008abb.png)

**Comment by H3idi-X** [comment]
Hi, If there is no response we will close this issue.
