### ISSUE TITLE
Future support for URP Light Layers and Shadow Layers?

### ISSUE THREAD

**Issue by kanzaki1201** [unity3d-jp/UnityChanToonShaderVer2_Project#113]
Hello there. Is there any plan to support light layers and shadow layers in the future?
Currently only the legacy way of light culling is supported I believe.

**Comment by H3idi-X** [comment]
Hi, We believe that we won't be able to give high priority to add those features at least this year.
But, we understand they are necessary. One thing we should mention is the new features would be implemented to [Unity Toon Shade](https://github.com/unity-technologies/com.unity.toonshader)r which is compatible with Universal Toon Shader.
