### ISSUE TITLE
Shader errors when building Unity project

### ISSUE THREAD

**Issue by ghost** [unity3d-jp/UnityChanToonShaderVer2_Project#115]
I'm having this very strange issue where when I build a project I'm doing for my college class using this shader, it gives me shader errors. I'm wondering if it's because of the DirectX version installed on my laptop or because of the lighting I generated for both scenes of a project I'm working on (to attempt to fix the dark lighting when loaded from another scene issue)? My build seems to complete though. 

**To Reproduce**
1. Generate the lighting first (Window > Rendering > Lighting > Generate Lighting)
2. Then try to build. 

**Expected behavior**
These errors should pop up on the screenshot below.

**Screenshots**
![Unity Shader Errors](https://user-images.githubusercontent.com/40510256/196601690-b94d53aa-ad0a-4402-a6a4-e550470150db.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10

Additional notes:
One of my instructors told me that it's either a DirectX or a loading issue, but I can't confirm it at this time.

**Comment by Nobuyuki-Kobayashi** [comment]
Hello. Thank you for contacting us.

It is difficult to give you a complete answer with the information you have given us at this time, as it is an error at build time, but judging from the fact that _ShadowCoord is giving you some errors, we believe it is most likely your system environment.

As a response, please try the following

1. replace UTS2 with the latest version, [UTS2.0.9](https://github.com/unity3d-jp/UnityChanToonShaderVer2_Project/blob/release/legacy/2.0/README.md). It is also possible that the version of UTS2 installed in your project is out of date. Please delete all related files and then reinstall the latest version of UTS2.

2. try replacing the video card driver of your PC with the latest version; if you are experiencing DirectX-related problems, please suspect a problem with the video driver once.

3. if you are not using the shader files that are causing the error, temporarily remove them from the project, build it, and see if the error does not appear.

The following shader files appear to be involved in the problem.
\Assets\Toon\Shader\Toon_ShadingGradeMap_TransClipping_StencilMask.shader
\Assets\Toon\Shader\Toon_DoubleShadeWithFeather_TransClipping.shader

Sincerely yours.
