### ISSUE TITLE
"Universal Render Pipeline/Toon" on open GL3.0

### ISSUE THREAD

**Issue by myzjy** [unity3d-jp/UnityChanToonShaderVer2_Project#116]
"Universal Render Pipeline/Toon" on open GL3.0 will cause some material errors, some material balls may not be rendered in the editor panel, and some material balls will appear as a ring of pop

windows10
unityVesion:2021.3.6f1c1
URPVesion:12.1.7
Error message image：
![image](https://user-images.githubusercontent.com/58101943/196912817-3686c458-f776-4f5b-a56e-12e2f3890659.png)
![image](https://user-images.githubusercontent.com/58101943/196913177-0772f341-f2a6-4dfd-99d1-046a96dc76e1.png)

**Comment by H3idi-X** [comment]
Hello.
In the inspector preview, some kinds of materials won't be rendered by design.
Because of the logic difference between GameView/SceneView rendering and editor panel.
