### ISSUE TITLE
Screen Space ShadeMaps

### ISSUE THREAD

**Issue by MrTdrake** [unity3d-jp/UnityChanToonShaderVer2_Project#120]
I am a developer hoping to use the toon shader in my project, but I needed to modify the shade map so that I can apply a stippling affect to the shader in screen space instead of unwrapping around the object which causes it to stretch and also doesn't quite fit the aesthetic I hope to achieve with the stippling. I was hoping to get any sort of direction on how I could go about adding that into the shader as of right now as there is a lot code and taking it all apart one by one is without having any knowledge of how it was put together is quite hard. I know this is a bit of a specific topic, but any help at all is appreciated and I just thought I would reach out in case you had any suggestions

**Comment by H3idi-X** [comment]
Hello.
But, unfortuantely, we do not have any suggestions on these specific topics, nor can we  provide programming knowledge on how to customize UTS for yourself. You might have to learn as you go along.
