### ISSUE TITLE
From unity 2021, downgrade to 2019 & shader is all pink

### ISSUE THREAD

**Issue by z79422957** [unity3d-jp/UnityChanToonShaderVer2_Project#121]
From unity 2021, downgrade to 2019, and then android build fails. Finally, I delete them and re-import shaders and models. They are all pink.What should I do? Thank you

unity2021.4.40
urp7.7.0

**Comment by z79422957** [comment]
![1673750504170](https://user-images.githubusercontent.com/16982190/212520183-d685ebd0-e430-4ecf-aa48-451a4cb01502.png)
![1673750671079](https://user-images.githubusercontent.com/16982190/212520241-037ab32d-d7b6-4933-ae28-94a180cf4985.png)
![1673750693602](https://user-images.githubusercontent.com/16982190/212520249-96b6d45a-0083-4be8-b559-432398b40839.png)

**Comment by H3idi-X** [comment]
Thanks for reporting. 
Will you please follow the format for bug reporting?

**Comment by H3idi-X** [comment]
It's not a UTS issue. Unity doesn't support downgrading project. 
If you want to do that,  you have to do that by your own risk.
