### ISSUE TITLE
MatCap is flickers in XR right eye When I use Vulkan URP

### ISSUE THREAD

**Issue by zgmtXAX** [unity3d-jp/UnityChanToonShaderVer2_Project#123]
Unity 2020.3.36f
URP 10.0.8 Oculus Fork [https://github.com/Oculus-VR/Unity-Graphics/](url)

MatCap is flickers in right eye like [https://github.com/unity3d-jp/UnityChanToonShaderVer2_Project/issues/119](url)
Is cannot see with OpenGLES3.0, but I Trying APPSW so I must use vulkan。

**Comment by sindharta-tanuwijaya** [comment]
Thank you for your report.
We do regret to inform you that we do not support the fork of URP you mentioned above, and therefore we would not be able to accommodate this request.

We hope that you will continue using UTS in your project.
