### ISSUE TITLE
hello, the shader unable to recieve shadow from another object. or I need to set some value in the sahder?

### ISSUE THREAD

**Issue by nu51313932** [unity3d-jp/UnityChanToonShaderVer2_Project#128]
hello, the shader unable to recieve shadow from another object. or I need to set some value in the sahder?

**Comment by Nobuyuki-Kobayashi** [comment]
Thank you for your inquiry. 
Regarding the issue where receive shadows are not appearing, it's important to note that UTS2, unlike other shaders designed for PBR, requires users to explicitly set the shadow color and further determine the extent of the shadowed area through a slider. 
For more detailed information, please refer to the manual.
