### ISSUE TITLE
TCTS_Outline.cginc

### ISSUE THREAD

**Issue by sator-imaging** [unity3d-jp/UnityChanToonShaderVer2_Project#13]
アルファ付きでスクショを取る時に抜けてしまって不便なので、アウトラインのアルファは１でいいのかなと思っています。

**Comment by Nobuyuki-Kobayashi** [comment]
確かにその通りですね。次のバージョンで修正しておきます。

**Comment by Nobuyuki-Kobayashi** [comment]
確認してみたのですが、アウトラインカラーのα値はv.2.0.5では1が入っていました。
スクショを取る時に抜けてしまうシェーダーはどれかわかりますでしょうか？

**Comment by sator-imaging** [comment]
すみません！ v2 系を使用しているのですが、v2.0.4 でアルファ処理が変わっていたようです。。。！
TCTS_Outline.cginc、101 行目の分岐がなく、return fixed4(Set_Outline_Color, 0.0f); で終わっているバージョンを使用していました。
確認不足ですみません。。。

**Comment by Nobuyuki-Kobayashi** [comment]
それは良かったです！では本件は解決ということでクローズしますね！
今後とも何かありましたらご連絡くださいませ！
