### ISSUE TITLE
Shader not reflecting baked/skybox lighting

### ISSUE THREAD

**Issue by ZHardcode** [unity3d-jp/UnityChanToonShaderVer2_Project#14]
I have been messing with this shader and I am a big fan of it as it's real-time shadows.
An issue I have been running into is the problem the title suggests, you can sort of overcome this with `Unlit_Intensity`. 

However, this creates another issue of it being too bright when you actually want it to be pitch black in pitch black lighting.

I don't know if this from settings I am unaware of or if this is genuinely something on the shader's end. But either way I'd appreciate a solution if possible.

Image references
https://imgur.com/a/p3Sq75V

**Comment by Nobuyuki-Kobayashi** [comment]
If your condition is same below:
* useing v.2.0.5
* no realtime light object and Skybox Material.
* Ambient Color is true black.
* Unlit_Intensity is Zero.
* All of Is_LightColor_* are checked
Under these conditions, your UTS2 materials show in black like the second screenshot. It is correct working.
In this case, you should increase the value of Unlit_Intensity. I recommend to set 1 or so.
And you increase the value of Unlit_Intensity, your UTS2 materials turns lighter, this is the function of built-in lighting.

The brightness of built-in lighting follows the brightness of Environment Lighting.
If you use IBL material as Skybox Material, Unlit_Intensity will follow the brightness of IBL.
(But it doesn't means UTS2 materials support IBL correctly like PBR materials.)

Finally UTS2 never catch effect of the lightmap of static objects like scene objects, if you need the effect of lightmap or GI, you must set light probes in your scene.
https://docs.unity3d.com/2018.3/Documentation/Manual/LightProbes-MovingObjects.html
The brightness of light probes can be tweaked from GI_Intensity.

More precisely, please read the manual below.
https://github.com/unity3d-jp/UnityChanToonShaderVer2_Project/blob/master/Manual/UTS2_Manual_en.md

**Comment by ZHardcode** [comment]
Ah, thanks for explaining.
