### ISSUE TITLE
Need Fix for UTS_ImageEffect_PPSv2's UTS_SobelColorEdgeDetection.shader

### ISSUE THREAD

**Issue by phields** [unity3d-jp/UnityChanToonShaderVer2_Project#15]
In Unity 2018.2  had to use

#include "PostProcessing/Shaders/StdLib.hlsl"

In Unity 2018.3 back to:

#include "Packages/com.unity.postprocessing/PostProcessing/Shaders/StdLib.hlsl"

**Comment by Nobuyuki-Kobayashi** [comment]
Thank you for your information.
I split the unitypackages for Unity 2018.2.x and Unity 2018.3.x.
It is because Unity2018.2.20 return its version no, as 201840 ^^;.
