### ISSUE TITLE
Render Texture でアルファ付きでスクショを撮る際の問題

### ISSUE THREAD

**Issue by sator-imaging** [unity3d-jp/UnityChanToonShaderVer2_Project#16]
ゲーム中では問題なく、キャラクターのピンナップ等を出力する際に Render Texture を使ってアルファ付きスクリーンショットを撮影する際にのみ、眉毛などのアルファが眉毛の物のみになってしまいます。
※※ 眉根などアルファが適用されている部分は、肌部分はカラーのみでアルファは考慮されず、アルファ付き PNG では眉毛のテクスチャ通りに抜けてしまう。

Toon_DoubleShadeWithFeather_TransClipping.shader
142            Blend SrcAlpha OneMinusSrcAlpha

を
Blend One OneMinusSrcAlpha に変えると回避はできますが、若干絵が変わります。
問題がそもそも上記シェーダーで対応すべきか、他のシェーダーの見直しをすべきかまでは確認していません。
下地の肌は Toon_DoubleShadeWithFeather です。

＝＝＝＝

それとは別に、アウトラインも TransparentCutout のせいなのか、GIF のようなガビガビのシルエットになってしまいます。※ 背景とアウトラインの境界のみ。肌の上などほかの何かがあれば設定どおり MSAA かかっているように見えます。

＝＝＝＝

言葉では説明しづらいのですが、スクショの撮影以外では問題ないので参考まで。

**Comment by Nobuyuki-Kobayashi** [comment]
アルファ付き出力ですが、Unity標準のRecorderからアルファ付き出力が利用出来ますので、そちらを使っていただいたほうがいいかもしれませんね。そちらは映像等にも使えるものですので、他にもマスクを作成したりいろいろできます。
