### ISSUE TITLE
複雑な形状のオブジェクトに対してCullOffを適応するとアーティファクトが発生することがある

### ISSUE THREAD

**Issue by skishida** [unity3d-jp/UnityChanToonShaderVer2_Project#19]
## 確認環境

* Windows10 1809
* Unity 2017.4.15f
* UTS 2.7.0.1

｢リリース｣からダウンロードした`UnityChanToonShaderVer2_Project-v.2.0.7.1.zip`内のプロジェクトを上記環境で開いて確認しています。

## キャラクターへの影響の確認手順

1. `Assets/Sample Scenes/ToonShader.unity` を開く
2. ヒエラルキー内`ToonShader_SD_unitychan_humanoid_Illust/Mesh_SD_unitychan/_body` に利用されているマテリアル(`Assets/Toon/Materials/ToonShader_Main`)を開き、次のような変更を加える
   1. シェーダーを`Toon_DoubleSideWithFeather`から`Toon_ShadingGradeMap_TransClipping`に変更する
   2. カリングモードをCullOffにする
   3. RimLightの LightDirectionMaskとAntipodeanRimlightをONにする

アーティファクトの発生が太腿のあたりで確認できます。
![2019-04-05-21-24-47](https://user-images.githubusercontent.com/13936540/55629957-76983e80-57ef-11e9-8a7c-f124b4ba3579.png)

## 最低限のマテリアル設定で再現させる手順

新しくマテリアルを作成し、次の設定を行っただけでも再現します。
1. シェーダーを`Toon_ShadingGradeMap_TransClipping`に変更する
2. カリングモードをCullOffにする
3. RimLightの LightDirectionMaskとAntipodeanRimlightをONにする
4. (そのままだとわからないので)BaseColor、1stShadeColor、2ndShadeColorを暗い色にする

![2019-04-05-21-29-52](https://user-images.githubusercontent.com/13936540/55629989-87e14b00-57ef-11e9-9fa7-3ac218e79c9c.png)

----

* 基本的にUTSのアウトライン用以外のバリエーションであればほぼ全てで上記のようなアーティファクトが見られます。
  * `NoOutline/ToonColor_ShadingGradeMap_Transparent`では発生しませんでした。
* 発生する箇所は、ポリゴンの辺上のみでした。
* ある程度複雑なジオメトリのオブジェクトに対して発生する傾向があるように見えます。一応、Unityで追加できるSphereでも(ほんのほんのわずかですが)発生することが見られました。
* あえて｢TransparencyLevel｣を0未満の値にしてみると、描画が表面と裏面が入り乱れた状態になります。
  * Level=0
    * ![2019-04-05-22-01-50](https://user-images.githubusercontent.com/13936540/55630013-9a5b8480-57ef-11e9-8d22-3b804c7edd5c.png)
  * Level=-0.1
    * ![2019-04-05-22-02-29](https://user-images.githubusercontent.com/13936540/55630026-a1829280-57ef-11e9-8da4-11909a3d32dc.png)
  * 発生するアーティファクトの位置は必ずこの入り乱れている状態の境界に位置しているように見えます。
    * (入り乱れる状態が正常なのかどうかは私には区別が付きません)
* もう少しTransparencyLevelを下げてみると、アルファチャンネルにも入り乱れている様子が確認できます。
  * Level=-0.5
    * ![2019-04-05-22-05-01](https://user-images.githubusercontent.com/13936540/55630042-aba49100-57ef-11e9-99c2-070a36d191ab.png)
* 状況によっては、シーンビューコントロールバーのライティングボタンのON/OFFでアーティファクトが見えなかったり見えたりと様子が変わりました。
* 
----

* CullOffで裏面の色が正しく｢塗りつぶされない｣(厳密に言えば異なるかと思いますが)
かつ
* ApRimlightで明るい色を指定したときに目立つ

という状況なのではないかなと考えています。よくよく同じ場所を見てみると、ApRimLightがオフでも本来と異なる極細のラインが描画されていることがわかります。そもそもCullOffにしなければ発生していないように思われるので(特にUTSだとOutlineありならCullOffでも裏面は出てきますし)かなり限定的で重要性も高くない問題かと思いますが、よろしくおねがいします。

**Comment by Nobuyuki-Kobayashi** [comment]
ご報告ありがとうございます。
こちらですが、自分の環境（Windows10/GeForce GTX 1060）では、

・ゲームビュー、シーンビュー共に通常状態では発生しない。
・シーンビューで、ライティングボタンをOFFにした時のみに発生する。この時、ゲームビューの表示は正常のまま。
・実際のライトをオフにしても、シーンビューのライティングボタンがONならば発生せず、ライティングボタンをOFFにした時にのみ発生する

以上の3点より、シーンビューとゲームビューのなんらかの表示精度の違いに基づくものと思われます。
シェーダーの挙動としましては、あくまでもゲームビューの表示が正しいものですので、そちらに問題がなければ「特に問題ない」と判断いたします。

またシーンビュー側のライティングボタンをON/OFFした場合の挙動に関しましては、Unity側の問題となりますが、シーンビューは必ずしもゲームビューと同じ表示をすることを保証するものではありませんので、仕様の範囲内かと考えます。

おそらくシーンビュー内での見え方は、使用している環境に依存すると思われますが、もし上記のアーティファクトがゲームビュー中でも発生するようでしたら、改めてご連絡いただければと存じます。
![0408-07_02](https://user-images.githubusercontent.com/3204820/55690686-c03f7f80-59cf-11e9-80e7-c296825bb176.png)
