### ISSUE TITLE
When using the TransClipping, the shadows wasn't cut as the object.

### ISSUE THREAD

**Issue by ealicesora** [unity3d-jp/UnityChanToonShaderVer2_Project#20]
I am using a texture's alpha channel for clipping but it seems that the shadow wasn't cut as the object does.  I don't know whether it's a bug.
![QQ图片20190521230617](https://user-images.githubusercontent.com/39162988/58107744-0ddd1800-7c1d-11e9-8b2e-10c7acf58743.jpg)
![QQ截图20190521230648](https://user-images.githubusercontent.com/39162988/58107779-23524200-7c1d-11e9-8e90-15e66e10df2f.png)

**Comment by Nobuyuki-Kobayashi** [comment]
Translucent alpha clipping is not supported for drop shadows. Therefore, this phenomenon is a specification. If you want to drop the clipped shadow, please use the cutout system.
