### ISSUE TITLE
Android OS6 XPeria 501SOで表示がされません。

### ISSUE THREAD

**Issue by wevet** [unity3d-jp/UnityChanToonShaderVer2_Project#21]
Shaderの勉強でUCTSを使用させて頂いているのですが、実機で表示がされない為、ご教授頂きたいと思っています。
エラー内容は以下となりました。
GLSL link error: Error: input vs_TEXCOORD2 not declared in output from previous stage
確認頂く事は可能でしょうか？

**Comment by Nobuyuki-Kobayashi** [comment]
ご連絡いただいたタイプのエラーは通常は出るものではありません（正しく言えば、今まで報告されたことがありません）ので、おそらくシェーダーのインストールに失敗していると思われます。
一度プロジェクト内のLibraryフォルダを削除した後で、最新のUTS2（現在はv.2.0.7.5）をマニュアルに従ってインストールし直してみてください。

ただUTS2はGLSLは一切使ってないので、GLSL link errorが出ること自体がおかしいですね。
何か一緒に使っている別のシェーダーが出しているエラーでないか、念のためチェックしてみるといいかもしれません。
もしくはAndroidのGraphic APIにVulkanもしくはOpenGL COREが入っているかチェックしてみるといいかもしれません。

**Comment by wevet** [comment]
ご連絡遅れまして大変申し訳ありませんでした。
こちらのレポジトリをDLして、Buildをしたのですが、エラーは確認されませんでした。
しかしながら、表示が反転されているように見受けられてまして、この場合は何かshader側の設定を直すことで改善されますでしょうか。

**Comment by wevet** [comment]
添付画像をお送りします。
![IMG_5216](https://user-images.githubusercontent.com/34650625/63241133-8475ca00-c28d-11e9-81b1-a7d2f2bd24e2.JPG)

**Comment by Nobuyuki-Kobayashi** [comment]
他では報告されていない症状ですので、最新のAndroid実機等でもお試しになることを強く推奨いたします。
（Andoridの場合、全ての機種でテストはもちろんできませんが、Galaxy S7などでテストしている結果では、特に問題は生じておりません。）
ちなみに、Unityエディタ上でAndorid開発環境でのゲームビュー表示と、実機での表示がまったく違うようでしたら、ハードウェア上で何かが足りていないのかもしれませんね…。

**Comment by wevet** [comment]
ご連絡ありがとうございます！
自分の端末設定などを確認させて頂きます。
お時間いただきまして有難うございました。
