### ISSUE TITLE
サンプルプロジェクトをOculusGo向けにビルドするときのエラーに関して

### ISSUE THREAD

**Issue by ishiiyuki** [unity3d-jp/UnityChanToonShaderVer2_Project#3]
ちょっと趣旨が違うかもしれないのとissue立てていいか迷ったんですけど
UnityChanToonShaderがここ最近初心者に使われてるので立てました。
Unity初心者の人がUniteのslideとかみてシングルパス設定でビルドしたとき
PostProcessingのShaderやImageEffectsのUTS_EdgeDetectで「undeclared identifier 'sampler_CameraDepthTexture' 」が出るんで初心者の人たち困ったりするから
回避方法とかREADMEとかにあるといいかなっと思いました。

**Comment by Nobuyuki-Kobayashi** [comment]
こちらと同じ原因らしいです。
https://issuetracker.unity3d.com/issues/gearvr-singlepassstereo-image-effects-are-not-rendering-properly

fogbugz には issue として登録されていて、直すつもりで進めているようです。
ただ、 single pass stereo rendering には2種類存在し（stereo instancing, multiview）両方とも完璧に対応するにはかなり気合が要りそうとのこと。

よろしければ、Voteに投票してもらえるといいかもしれませんね。
