### ISSUE TITLE
Broken link in license terms

### ISSUE THREAD

**Issue by ewjordan** [unity3d-jp/UnityChanToonShaderVer2_Project#30]
In the license at https://unity-chan.com/contents/license_en/ the clause that seems like it should apply to the code in this repo reads:

```
(3) "Digital Asset Data of Company's Characters"
Digital Asset Data of Company's Characters means digital data of the Company's Characters which were made into a format usable by standard computers.
Users of the Company's Characters may create derivative works of the Company's Characters under this License by using the Digital Asset Data of Company's Characters.
Further, if a portion of the Digital Asset Data of Company's Characters is converted to items other than the Company's Characters, Users shall comply only with the separately defined "Asset Store Terms of Use and End-user License Agreement" (http://japan.unity3d.com/company/legal/as_terms) and not with this License.
```

But http://japan.unity3d.com/company/legal/as_terms is a broken link (though https://unity3d.com/legal/as_terms works).

As it stands this renders the project effectively unlicensed, would it be possible to add an explicit license in the repo itself, even if it just points to a working Unity license link?

**Comment by ACIIL** [comment]
The UTS2 **Shader** license does need clarification, and in licensing terms Github understands and accepts and _independent_ of the Unity Chan Character. This legal uncertainty is interfering with legal protections to fork and modify the shader as is, and for what projects that go from FOSS or more restrictive.

**Comment by H3idi-X** [comment]
Thanks for the suggestion.
We will use different licenses for shader codes and data.
Shader will be under [Unity Companion License](https://unity3d.com/jp/legal/licenses/Unity_Companion_License).
Sample scene and model data should be under [UCL](https://unity-chan.com/contents/guideline_en/)

This repo will be renovated soon.
