### ISSUE TITLE
[URP]Built-in vector for light direction is not pointing from angle

### ISSUE THREAD

**Issue by hiroki-o** [unity3d-jp/UnityChanToonShaderVer2_Project#31]
ビルトインライトディレクションベクトルの設定方向が「正面から」になっていて、「斜め上から」になっていない

2020/01/14
調査中。Legacy パイプラインで、一つもディレクショナルライトがない状態で WorldLightPos0 に入っている値が入っているのは特に仕様でないような。別方法で実装する必要ががあるでしょう。

2020/01/21
一つもDirectional Light がない状態だと Sunlightの値をもとにこの値を計算するはずだが単純に (0,0,-1)を入れたままにしているのでは？

2020-01-21
•  が何か案を試す

**Comment by Nobuyuki-Kobayashi** [comment]
Done with Commit No. : 038f79b
