### ISSUE TITLE
UniversalRP:Clipping option is not displaying for DOupbleShadeWithFeather shaders

### ISSUE THREAD

**Issue by hiroki-o** [unity3d-jp/UnityChanToonShaderVer2_Project#33]
DoubleShadeWithFeather系シェーダーで、Clipping ModeをOnにした時に、For_Clipping or _TransClipping Shader用のオプションが表示されなくなった。

**Comment by Nobuyuki-Kobayashi** [comment]
Done with Commit No. : 038f79b
