### ISSUE TITLE
UniversalRP:Render Queue config get reset when revered to Custom UI

### ISSUE THREAD

**Issue by hiroki-o** [unity3d-jp/UnityChanToonShaderVer2_Project#34]
・Show All Propertiesで設定したRender Queueの設定（Emerald:Transparent / Emerald_Inside:Geometry）が、Custom UIに戻すとおそらく初期値にリセットされてしまう（Emerald:AlphaTest / Emerald_Inside:AlphaTest）。 ⇒結果、カスタムレンダーキューの値が保持できない

**Comment by Nobuyuki-Kobayashi** [comment]
Done with Commit No. : 541b79b
