### ISSUE TITLE
HDRP/URP support

### ISSUE THREAD

**Issue by ShanguUncle** [unity3d-jp/UnityChanToonShaderVer2_Project#38]

**Comment by matEhickey** [comment]
You can use the 'urp-master' branch which is usable.  
Although, it also seam to have a huge performance impact on mobile (for now i hope), but maybe it's normal, i never used the builtin-renderer version before to compare.

**Comment by ShanguUncle** [comment]
Thank you very much, this problem is solved after I reimport.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mts DDR"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月15日(星期三) 上午6:31
收件人:&nbsp;"unity3d-jp/UnityChanToonShaderVer2_Project"<UnityChanToonShaderVer2_Project@noreply.github.com&gt;;
抄送:&nbsp;"Gushijie"<1786570525@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [unity3d-jp/UnityChanToonShaderVer2_Project] HDRP/URP support (#38)





 
You can use the 'urp-master' branch which is usable.
 Although, it also seam to have a huge performance impact on mobile (for now i hope), but maybe it's normal, i never used the builtin-renderer version before to compare.

**Comment by ColinAllmanGame** [comment]
Is there a branch to pull to try out or help on the shader in HDRP?

**Comment by matEhickey** [comment]
I dont know the difference, but there are 2, hdrp/dev and hdrp/dev-tosh

**Comment by H3idi-X** [comment]
Both HDRP and URP compatibility are still in progress. I will provide official support toon shaders of both render pipelines. But they will not be in this repository.
