### ISSUE TITLE
UTS V2 Universal RP: Transparent material render queue collapses when pressing the play button.

### ISSUE THREAD

**Issue by H3idi-X** [unity3d-jp/UnityChanToonShaderVer2_Project#39]
How to produce.

- Set Transparent mode is on and AutoQueue is active on a material.
- Press play button in the Editor..
- The material renderQueue is set to RenderQueue.Geometry.

**Comment by Nobuyuki-Kobayashi** [comment]
Done with Commit No. : 541b79b
