### ISSUE TITLE
bug fix,  _Offset_Z  support for vrchat mirrors

### ISSUE THREAD

**Issue by ACIIL** [unity3d-jp/UnityChanToonShaderVer2_Project#4]
Currently, _Offset_Z it not correctly handled in vrchat mirrors. 
Here is the fix, at:

https://github.com/unity3d-jp/UnityChanToonShaderVer2_Project/blob/348c83694e125a5900342ae67a4dcced55ae7b18/Assets/Toon/Shader/UCTS_Outline.cginc#L48

remove the `normalize()`,  somehow the length between the camera position and vertex matters, i am not sure why this works.  Here is the background how mirrors are implemented:
https://wiki.unity3d.com/index.php/MirrorReflection3
My poor guess is the mirror's camera position becomes the "mirror object" world position and that distance is used when the camera's world matrix fuses with the players world matrix into clip space.

**Comment by Nobuyuki-Kobayashi** [comment]
Thank you for your issues. I'll check this point.

**Comment by Nobuyuki-Kobayashi** [comment]
Thank you for your contribution.
I've fixed this bug and released v.2.0.4.2, today.
