### ISSUE TITLE
UTS2 UWP can’t be installed into a project as .unitypackage, when legacy UTS2 is installed in it.

### ISSUE THREAD

**Issue by H3idi-X** [unity3d-jp/UnityChanToonShaderVer2_Project#42]
Because of path of the path of UCTS_Outline.cginc.
![image](https://user-images.githubusercontent.com/4477357/78000106-b5af9000-736e-11ea-836e-5e1faf43e232.png)

**Comment by nyaa-kobayashi** [comment]
Fixed #e0667a8
