### ISSUE TITLE
shader error in urp: invalid subscript 'shadowCoord'

### ISSUE THREAD

**Issue by Personuo** [unity3d-jp/UnityChanToonShaderVer2_Project#44]
2020-05-12
☑  QA if the shader error is fixed.

Now, the shader is compatible with SRP 7.1.7, 7.3.1, 8.0.1, 9.0.0preview.

**Comment by kaku1923** [comment]
@cn914287516 
I encountered the same error when I upgrade to URP 7.3.1,
and the error appears when I enable the shadow cascades.

I also found that there are two ways to fix it.

1. Downgrade to URP 7.1.8
2. In `UniversalToonBody.hlsl`
line 558:
```diff
-#  ifdef _MAIN_LIGHT_SHADOWS
+#if defined(REQUIRES_VERTEX_SHADOW_COORD_INTERPOLATOR)
```
line 562:
```diff
-#  ifdef _ADDITIONAL_LIGHTS
+#if defined(REQUIRES_WORLD_SPACE_POS_INTERPOLATOR)
```
line 997:
```diff
-#  ifdef _MAIN_LIGHT_SHADOWS
+#if defined(REQUIRES_VERTEX_SHADOW_COORD_INTERPOLATOR)
```
line 1001:
```diff
-#  ifdef _ADDITIONAL_LIGHTS
+#if defined(REQUIRES_WORLD_SPACE_POS_INTERPOLATOR)
```

**Comment by Personuo** [comment]
> @cn914287516
> I encountered the same error when I upgrade to URP 7.3.1,
> and the error appears when I enable the shadow cascades.
> 
> I also found that there are two ways to fix it.
> 
> 1. Downgrade to URP 7.1.8
> 2. In `UniversalToonBody.hlsl`
>    line 558:
> 
> ```diff
> -#  ifdef _MAIN_LIGHT_SHADOWS
> +#if defined(REQUIRES_VERTEX_SHADOW_COORD_INTERPOLATOR)
> ```
> 
> line 562:
> 
> ```diff
> -#  ifdef _ADDITIONAL_LIGHTS
> +#if defined(REQUIRES_WORLD_SPACE_POS_INTERPOLATOR)
> ```
> 
> line 997:
> 
> ```diff
> -#  ifdef _MAIN_LIGHT_SHADOWS
> +#if defined(REQUIRES_VERTEX_SHADOW_COORD_INTERPOLATOR)
> ```
> 
> line 1001:
> 
> ```diff
> -#  ifdef _ADDITIONAL_LIGHTS
> +#if defined(REQUIRES_WORLD_SPACE_POS_INTERPOLATOR)
> ```

Thank you for help! I try this and success!
But I use toony shader for my project now.

**Comment by Nobuyuki-Kobayashi** [comment]
Fixed in https://github.com/unity3d-jp/UnityChanToonShaderVer2_Project/tree/e7ee9605f98ec3ea9575a52511a9aee0e535a73a
