### ISSUE TITLE
What's the most compatible batching way for UTS?

### ISSUE THREAD

**Issue by JyuuAra** [unity3d-jp/UnityChanToonShaderVer2_Project#45]
I see SRP Batcher is checked in UTS2URPPipelineAsset, will UniversalToon support SRP Batcher?
Also, which is the best way batching a lot of small UTS models under stardard pipeline?
Static batching or Dynamic batching(Maybe not work because UTS is a multi pass shader).
Or should GPU Instancing work?
I have tried to test with hundreds UTS  objects (same mesh, same material, with low vertices just like cube), neither SRPBatcher nor GpuInstancing takes effect.
So I wonder if  there's any configuration I miss or UTS doesn't support them currently.
Any advice would be appreciated.Thanks.

**Comment by Nobuyuki-Kobayashi** [comment]
Hi, JyuuAra, thank you for your issue.
I've heard SRPBatcher don't work in the multi pass shader like UTS2 from our team.
For this purpose, you had better use a simple shader like Unlit or so.
It is one of the specifications of URP,  so there might be no way to solve it.

**Comment by yangzijianGit** [comment]
gpu instance is supported. but the shader don't have   #pragma multi_compile_instancing , use it in the pass code.
