### ISSUE TITLE
Singlepass compatible. 

### ISSUE THREAD

**Issue by LongChau** [unity3d-jp/UnityChanToonShaderVer2_Project#46]
Hi guys, My current project is MagicLeap (MixedReality) game and I'm using this Toon_DoubleShadeWithFeather.shader for many objects in my game. But a weird thing happens, I can only see the object in the left eye while the right eye is rendered nothing. I figure out that this shader is not compatible with single-pass render.

There are 2 solutions: First one is enable force multipass in magic leap setting.
<img width="554" alt="image" src="https://user-images.githubusercontent.com/40262027/81365464-5fbecc80-9112-11ea-93df-f2c9efc0a88e.png">
Another solution is upgrading the shader to become compatible with single pass. According to this: https://docs.unity3d.com/Manual/SinglePassInstancing.html to use SinglePassInstacing advantages. But I don't know how to upgrade that shader. Does anyone know how?

**Comment by Nobuyuki-Kobayashi** [comment]
Hi, Long Châu, thank you for your issue.
I think UTS2 needs 2 pass rendering for the outline feature in the basic architecture, so I recommend to use "Force Multipass" option for Magic Leap.
