### ISSUE TITLE
urp/master build error on android platform

### ISSUE THREAD

**Issue by koseyile** [unity3d-jp/UnityChanToonShaderVer2_Project#51]
there are errors when build ump/master on android platform.
like this:
Assets/Toon(Universal)/Editor/UniversalToonGUI.cs(12,37): error CS0246: The type or namespace name 'BaseShaderGUI' could not be found (are you missing a using directive or an assembly reference?)

**Comment by H3idi-X** [comment]
We will support Vulcan in official release. However it would not be Unitychan /Universal toon shader. We'll provide another toon shader.
