### ISSUE TITLE
How to use it without Lights in the Scene? (I am looking for something like Shader "Toon/Basic")

### ISSUE THREAD

**Issue by saorisato** [unity3d-jp/UnityChanToonShaderVer2_Project#54]
Hi everyone,

my scene has no Lights. How can I make UnityChanToonShade look like Shader "Toon/Basic"?

It should display colors even without Lights in the scene?

Thanks

**Comment by saorisato** [comment]
!

**Comment by higeometry** [comment]
I believe It won't be supported in our shaders for a while as it would make confusion.
If there is no light, nothing should be drawn for usual cases.
