### ISSUE TITLE
UnityChanToonShaderVer2_Project (Zip)  urp is 404

### ISSUE THREAD

**Issue by yimengfan** [unity3d-jp/UnityChanToonShaderVer2_Project#55]

**Comment by EP-Toushirou** [comment]
doesn't find urp sample project.

**Comment by EP-Toushirou** [comment]
> _No description provided._

https://github.com/unity3d-jp/UnityChanSSU
URP Release demo.

**Comment by yimengfan** [comment]
is null

**Comment by EP-Toushirou** [comment]
> is null

not master branch, look at the release.
https://github.com/unity3d-jp/UnityChanSSU/releases

**Comment by H3idi-X** [comment]
Thanks for introducing UnityChanSSU.

We are not providing zip in this repo. This place is for development.
If necessary, will you please use the above?
