### ISSUE TITLE
Documentation: Shader Name of UniversalToon

### ISSUE THREAD

**Issue by tarepan** [unity3d-jp/UnityChanToonShaderVer2_Project#56]
## Summary
Latest shader name is `Universal Render Pipeline/Toon`, but documents use the name `UTS/UniversalToon`.  
Which name is intended one?  

## Configuration
- `dev/urp` branch 2103762f4d62702e290f26307bdaee6faacbb6fb

## Problems
Current URP-compatible UTS shader is named as `Universal Render Pipeline/Toon` after commit 7ae2f23eabc0b6095246f7bb2bb59a0b6e9bce56.  
https://github.com/unity3d-jp/UnityChanToonShaderVer2_Project/blob/2103762f4d62702e290f26307bdaee6faacbb6fb/Runtime/Shaders/UniversalToon.shader#L7

In contrast, document use the name `UTS/UniversalToon`.  
https://github.com/unity3d-jp/UnityChanToonShaderVer2_Project/blob/2103762f4d62702e290f26307bdaee6faacbb6fb/README.md#L13

In my understanding, this toon shader is single Uber shader, so there is only one shader name.  
Which is correct name?  

## Comment
Thunks for your great toon shader library.  
I love UTS projects.  
If this is non-latest documentation problem, I am grad to update documents & make pull request to fix this problem.  
If there are some deep problem and my issue is non-sense, very sorry for bothering you.

**Comment by H3idi-X** [comment]
Thanks for the information and sorry for this confusion.
We have decided to make new toon shader which should be named Unity Toon Shader.
We'll continue to support urp-2.2.x for a while. but the official release would be named  Unity Toon shader ver 1.00 and that shader would be a bit different from Unitychan / Universal toon shader.
