### ISSUE TITLE
Clearify UTS2 Shader license in githubs terms with a LICENSE.md

### ISSUE THREAD

**Issue by ACIIL** [unity3d-jp/UnityChanToonShaderVer2_Project#57]
The UTS2 **Shader** license needs clarification, and in licensing terms Github understands and accepts and _independent_ of the Unity Chan Character. This legal uncertainty is interfering with legal protections to fork and modify the shader as is, and for what projects that go from FOSS or more restrictive.

**Comment by H3idi-X** [comment]
I agree with you. We will separate shader license and data license.
Shader will be under [Unity Companion license](https://unity3d.com/jp/legal/licenses/Unity_Companion_License) .
Sample model and scene data will be under [UCL.](https://unity-chan.com/contents/guideline_en/)

This repository will be renovated soon.
