### ISSUE TITLE
Questions about the official release for HDRP

### ISSUE THREAD

**Issue by ogre-ku** [unity3d-jp/UnityChanToonShaderVer2_Project#58]
The one for URP has been officially released, but when will the official release for HDRP be available?

**Comment by H3idi-X** [comment]
Hi, Thanks for asking. But, both, HDRP and URP have not been officially released yet. One of my coworkers might have tweeted once. but it doesn't follow we've officially rereleased. Both are still in progress.  You can use experimental implementation of HDRP version dev/hdrp for now.

**Comment by H3idi-X** [comment]
One thing I forgot add. We can not support URP and HDRP versions and can't give answers for questions yet.
