### ISSUE TITLE
Confirmation of the difference between the answer of issues 58 and the content of the Release log

### ISSUE THREAD

**Issue by seoyeon01** [unity3d-jp/UnityChanToonShaderVer2_Project#65]
The answer to "https://github.com/unity3d-jp/UnityChanToonShaderVer2_Project/issues/58" 
indicates that neither HDRP nor URP has been officially published.
(on 2020.10.20)

However, the latest release log for "https://github.com/unity3d-jp/UnityChanToonShaderVer2_Project/releases/tag/urp-2.2.0" specifies the official launch of the URP.
(on 2020.07.28)

1. Is the official release of the URP correct? (2.2.0)
2. Can you tell me what's going on with HDRP (a rough release plan)?

**Comment by H3idi-X** [comment]
Sorry for the confusion. We'll support URP-2.2.0 or later for a while. but, Our true official release version should be released through our package manager system.
