### ISSUE TITLE
Transparent cutout doesn't properly work on Unity 2019

### ISSUE THREAD

**Issue by Quote-2004** [unity3d-jp/UnityChanToonShaderVer2_Project#66]
This shader, like many others, suffer problems with transparent cutout on Unity 2019.

![UTSPROBLEM](https://user-images.githubusercontent.com/52431745/104627872-2f460f80-565d-11eb-9ad0-89b0c1b862cb.PNG)

In a model I use for an avatar, this is how it looks like in 2019, it is not supposed to look like that.

Maybe fix it before everything eventually migrates to Unity 2019 and later?

**Comment by The-Patriach** [comment]
In UniversalToon.Shader there's a typo on line 24. It's [Enum(OFF,0,ON,1)] instead of [Enum(OFF,0,ON,1,]

**Comment by H3idi-X** [comment]
Thanks for reporting. We'll fix this typo at the next release.

**Comment by H3idi-X** [comment]
Hi, there.

We released 2.2.2 today.
Will you please try this?

https://github.com/unity3d-jp/UnityChanToonShaderVer2_Project/releases/tag/urp-2.2.2
