### ISSUE TITLE
Use UTS2 In Unity 2020 (URP 7.x ->10.x)

### ISSUE THREAD

**Issue by seoyeon01** [unity3d-jp/UnityChanToonShaderVer2_Project#67]
2.2.0 URP UTS2 will not be compiled in the latest unity (recently identified in 2020.2.1f1).

This seems to be a problem as the URP version changes from 7.x to 10.x.
It's been a long time since I haven't heard about update of UTS2, 
so i share how to use UTS2 in Unity 2020.

This temporarily eliminates errors and allows for verification of operation,
but does not guarantee complete normal functionality.

Image below are modifications to the codes available in Unity 2020 (URP 10.x)
----
1. UniversalToonBodyDoubleShadeWithFeather.hlsl 
![2](https://user-images.githubusercontent.com/48429544/104811982-750ffd00-5842-11eb-9fdc-2b059c0f7253.png)

2. UniversalToonBody.hlsl
![1](https://user-images.githubusercontent.com/48429544/104811932-3c702380-5842-11eb-8376-cff28c6ceae4.png)

3. UniversalToonBodyShadingGradeMap.hlsl
![3](https://user-images.githubusercontent.com/48429544/104812010-a5579b80-5842-11eb-9072-3a6140fe4eda.png)

4. UniversalToon.shader (This is not issue about URP 7.x -> 10.x. anyway.. there is corrected typo in enum syntex)
![4](https://user-images.githubusercontent.com/48429544/104812033-c7511e00-5842-11eb-956a-2ce4a0bb61d6.png)

----

![이미지 364](https://user-images.githubusercontent.com/48429544/104812065-0c755000-5843-11eb-8591-e6fb9d79874d.png)

It's a very ignorant method, but i'm able to use UTS2 in the UNITY 2020 versiont anyway.

I hope to hear the news about UTS2 continuously.

**Comment by ghost** [comment]
Hello,I noticed that some modifications`s location don`t match you mentioned

1 is in UniversalToonBodyDoubleShadeWithFeather.hlsl
2 is in UniversalToonBody.hlsl
3 and 4 are in their location

I tried, it does work on my Unity2020.2.1f1c1 with URP10.2.2 thanks alot

**Comment by Fzcpp** [comment]
thx~

**Comment by seoyeon01** [comment]
> Hello,I noticed that some modifications`s location don`t match you mentioned
> 
> 1 is in UniversalToonBodyDoubleShadeWithFeather.hlsl
> 2 is in UniversalToonBody.hlsl
> 3 and 4 are in their location
> 
> I tried, it does work on my Unity2020.2.1f1c1 with URP10.2.2 thanks alot

I modified the part where I wrote the wrong file name.
I'm glad to hear that it works properly.

**Comment by MuzaibRanjha** [comment]
Thanks, It fixed the issue.

**Comment by H3idi-X** [comment]
Thank you for reporting and providing tips to make UTS work on Universal RP 10.x.
Apology that UTS2 not working properly on URP 10.x and this late reply.
We are looking into this now and hopefully release new version with URP 10.x compatibility.

**Comment by H3idi-X** [comment]
Hi, there.

We released 2.2.2 today.
Will you please try this?

https://github.com/unity3d-jp/UnityChanToonShaderVer2_Project/releases/tag/urp-2.2.2

**Comment by seoyeon01** [comment]
> Hi, there.
> 
> We released 2.2.2 today.
> Will you please try this?
> 
> https://github.com/unity3d-jp/UnityChanToonShaderVer2_Project/releases/tag/urp-2.2.2

The problem occurs in the same way as the reproduction method mentioned in the previous mail.
The problem that occurred when changing the shader of the hat is solved.
However, if you change the shader of another object in the same way, an error occurs.

Shader error in `Universal Render Pipeline/Toon' : invalid subscript 'vertexSH' at Assets/UTS2/Runtime/Shaders/UniversalToonBodyDoubleShadeWithFeather.hlsl(41) (on d3d11)

I'm attaching a related photo.

Thank you.  
![image](https://user-images.githubusercontent.com/48429544/108781133-c67f7a80-75ac-11eb-86eb-5054f0ac40ac.png)

**Comment by H3idi-X** [comment]
Thanks and sorry for reporting again.
I'll look into the problem.

**Comment by H3idi-X** [comment]
I found this is related to LIGHT_MAP and not only 10.x, it occurs in former version too.

**Comment by H3idi-X** [comment]
Hi, we found that fixing this issue is hard without making drastic restructuring. If we fixed this vertxSH error, the next problem is texture number limitation and we will sometime come to see an error, maximum ps_4_0 sampler register index (16) exceeded. 

We had been spending long time to deal with this problem and we have decided to make new shader drastically improved, which,　we believe, can get over this issue. Will you please refrain from using light map, checking static in the inspector to UTS objects, for a certain period?

We started the new project a few weeks ago. Currently, we are mainly working on the legacy shader integration similar to Universal and HDRP. Next, we focus on HDRP improvement. Reducing the number of textures will be the next.

Thank you.
UTS team.

**Comment by Slaghton** [comment]
This shader doesn't accept shadows from other objects correct?

**Comment by H3idi-X** [comment]
It does. the points are

1. Setting the 1st shade map color.
2. Enabling Receive System Shadow.

![image](https://user-images.githubusercontent.com/4477357/113540933-1d508900-961c-11eb-931f-7d2494e08ab0.png)

**Comment by H3idi-X** [comment]
As this is opened for other issues, will you open other issues if you are not able to solve what you've asked?

Thanks,
UTS Team.
