### ISSUE TITLE
Toon shader build error: Undeclared identifier 'input'

### ISSUE THREAD

**Issue by haoyuant** [unity3d-jp/UnityChanToonShaderVer2_Project#74]
Hi I found this error when using UTS URP (I tried both v2.2.0 and v2.2.2)
Unity version: 2021.1.1f1
OS: MacOS

I also try to open the KAGURA scene directly from https://github.com/unity3d-jp/UnityChanKAGURA, but what I got was all pink. Does anyone know how to fix this problem?
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/45114697/116815047-19724100-ab9f-11eb-8eb5-8a245b2a44bb.png">

**Comment by haoyuant** [comment]
And this is the line that throws the error 
<img width="845" alt="image" src="https://user-images.githubusercontent.com/45114697/116815132-7a017e00-ab9f-11eb-9b13-1eb28e13b5b9.png">

**Comment by H3idi-X** [comment]
Hi, we released urp/2.2.3 today.
Will you please try that one?

https://github.com/unity3d-jp/UnityChanToonShaderVer2_Project/releases/tag/urp-2.2.3

**Comment by haoyuant** [comment]
Thanks @higeometry , I'll try that out later and let you know the result : )

**Comment by haoyuant** [comment]
Thanks for the excellent work, I've tried the new release and it works well. Previously when I manually fixed the compiling error and set the workflow mode of the material to ShadingGradeMap, it would still mess up the rendering, but it seems that the new release has nicely fixed this issue, and the rendering quality looks better (maybe psychological effect, lol) \(^o^)/
