### ISSUE TITLE
Does not rendered in right eye while using Single Pass Instanced rendering

### ISSUE THREAD

**Issue by RamType0** [unity3d-jp/UnityChanToonShaderVer2_Project#75]
It seems that UTS2.0.7(legacy) does not rendered in right eye while using Single Pass Instanced rendering.
AFIK, SinglePass(Stereo) rendering is deprecated in Unity2020 and we should choose MultiPass or SinglePassInstanced.
Using MultiPass rendering will be resulted in poor performance, so we want to choose SinglePassInstanced.

**Comment by H3idi-X** [comment]
Hi, Thanks for the report.
But, we have no plans to update legacy Unity-chan toon shader, We'll consider to adopt your susgestion in our new toon shader project, which is in progress in the following repo.
https://github.com/unity-technologies/com.unity.toonshader
