### ISSUE TITLE
Shader ignores fog ?

### ISSUE THREAD

**Issue by Kulgann** [unity3d-jp/UnityChanToonShaderVer2_Project#76]
Hi there,  I noticed that the shader ignores the scene fog settings. Looking at the frag functions everything seems to be set up except calling the MixFog macro. Adding this line "finalRGBA.rgb = MixFog(finalRGBA.rgb, inputData.fogCoord);" fixes the issue. I'm wondering if this is intentional and is there a way to use this shader  with fog ?

**Comment by H3idi-X** [comment]
Can I ask which render pipeline version of UTS you are talking about? Legacy or Universal?

**Comment by Kulgann** [comment]
> Can I ask which render pipeline version of UTS you are talking about? Legacy or Universal?
Yeah sorry I forgot. Its the URP version. The project is on URP 7.3.1. 
I got the version from here https://github.com/Unity-Technologies/com.unity.toonshader

**Comment by H3idi-X** [comment]
Apologies for this late reply. This is by design and we believe it should be difficult to support fog for outline passes. We have no plans to support fog so far.
