### ISSUE TITLE
Error on Shader : implicit truncation of vector type

### ISSUE THREAD

**Issue by Yuki-Soul** [unity3d-jp/UnityChanToonShaderVer2_Project#79]
i got error on shader UniversalToon after importing project.json in to my unity 2021.1.12 ver. 
when i using toon shader it just showing outline. so i guess i must fix the error on shader first.
is this just happen for me? how can this be fixed?

**THIS IS THE ERROR MESSAGE:**
implicit truncation of vector type
Compiling Vertex program with _OUTLINE_NML _IS_OUTLINE_CLIPPING_NO
Platform defines: UNITY_ENABLE_REFLECTION_BUFFERS UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_PBS_USE_BRDF1 UNITY_SPECCUBE_BOX_PROJECTION UNITY_SPECCUBE_BLENDING UNITY_ENABLE_DETAIL_NORMALMAP SHADER_API_DESKTOP UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_LIGHTMAP_RGBM_ENCODING UNITY_PASS_SRPDEFAULTUNLIT
Disabled keywords: _IS_OUTLINE_CLIPPING_YES _OUTLINE_POS UNITY_NO_DXT5nm UNITY_ENABLE_NATIVE_SHADOW_LOOKUPS UNITY_METAL_SHADOWS_USE_POINT_FILTERING UNITY_NO_SCREENSPACE_SHADOWS UNITY_PBS_USE_BRDF2 UNITY_PBS_USE_BRDF3 UNITY_NO_FULL_STANDARD_SHADER UNITY_HARDWARE_TIER1 UNITY_HARDWARE_TIER2 UNITY_HARDWARE_TIER3 UNITY_COLORSPACE_GAMMA UNITY_HALF_PRECISION_FRAGMENT_SHADER_REGISTERS UNITY_LIGHTMAP_DLDR_ENCODING UNITY_LIGHTMAP_FULL_HDR UNITY_VIRTUAL_TEXTURING UNITY_PRETRANSFORM_TO_DISPLAY_ORIENTATION UNITY_ASTC_NORMALMAP_ENCODING SHADER_API_GLES30

**Comment by riina** [comment]
Just my two cents, that's a warning that always seems to happen, even when the shader functions normally. Nothing to be worried about there.
I tried adding the package on 2021.1.12f1 on git tag urp-2.2.3, and it seems to work alright out of the box.
*Maybe* you didn't set your SRP settings asset to your URP RP asset and it's not rendering because of that?

**Comment by Yuki-Soul** [comment]
owh, thanks it's fixed now. i try to delete and recreate UniversalRenderPipelineAsset, after that i reassign it again on graphics then the shader works again (but the warning on shader still there). still wondering whats wrong before, but anyway it fixed now. thank you :)
