### ISSUE TITLE
アウトラインにちらつきが発生する

### ISSUE THREAD

**Issue by lilxyzw** [unity3d-jp/UnityChanToonShaderVer2_Project#82]
# 現象
SceneにLightProbeが存在するとき、カメラの位置や角度によってアウトラインにちらつきが発生するように見えます。
Outline Pass内のタグに"LightMode"="ForwardBase"を追記することで現象が改善されることを確認していますが、こちらでは十分にデバッグを行えていないためそちらでもご確認いただければ幸いです。
# 再現方法
- Unityバージョン: 2018.4.20f1
- パイプライン: Built-In RP
1. SceneにModeがBakedのDIrectional Lightを設置、現象が確認しやすいようにリアルタイムライトは無い状態にする
2. Plane等で簡易的な地形を作成しLightmap Staticにする
3. 地形に合わせLightProbeを配置、LightProbeの陰影が強いと確認しやすい
4. ライトをベイクし、Scene内にUTS2でアウトラインを出したマテリアルを適用したメッシュを配置

**Comment by Nobuyuki-Kobayashi** [comment]
ご報告ありがとうございます。
本件、別の方からも同様の報告を受けておりますので、調査させていただきます。
少々お時間をいただければと存じます。

**Comment by Nobuyuki-Kobayashi** [comment]
修正バージョンのシェーダーのみのUnitypackageです。
よろしかったらテストをしてみてくださいませ。
https://github.com/unity3d-jp/UnityChanToonShaderVer2_Project/blob/dev/legacy/2.0.8/UTS2_ShaderOnly_v2.0.8_Release.unitypackage

**Comment by lilxyzw** [comment]
修正ありがとうございます。
v2.0.8に更新することでUnity上でもVRChat上でもアウトラインのちらつきが発生しなくなりました。

**Comment by Nobuyuki-Kobayashi** [comment]
>  lilxyzwさん
ご確認ありがとうございます。
今後もよろしくお願いします！
Thank you for your collaboration!
