### ISSUE TITLE
HDRP shader Does not receive punctual lights shadows

### ISSUE THREAD

**Issue by Kulgann** [unity3d-jp/UnityChanToonShaderVer2_Project#86]
This is when the plane is using the toon shader 
![No Shadows](https://user-images.githubusercontent.com/4999276/129678891-4c31058a-fd1a-49cb-b22d-b3d74da4cc81.png)
And this is the plane using the HDRP Lit shader with correct shadows
![correct shadows](https://user-images.githubusercontent.com/4999276/129700949-412b340f-8a4f-42cd-9fae-39fe39e36740.png)

**Comment by H3idi-X** [comment]
Hi, Thanks for reporting.
Let me clarify some. Are you using Unity Toon Shader HDRP?
https://github.com/Unity-Technologies/com.unity.toonshader

As far as I tested, shadow drops to Unity Toon Shader Material floors.

The followings are the way I confirmed:

1. Open LIightAndShadowBakedLight scene.
2. Change the shader of SceneElements material to HDRP/Toon.
3. Change the 1st shade map color to black or something like that.

Will you please try like above?

![image](https://user-images.githubusercontent.com/4477357/129723926-f77a684d-97b1-4b6e-8418-75d67c6f70a2.png)

**Comment by Kulgann** [comment]
> Hi, Thanks for reporting.
> Let me clarify some. Are you using Unity Toon Shader HDRP?
> https://github.com/Unity-Technologies/com.unity.toonshader
> 
> As far as I tested, shadow drops to Unity Toon Shader Material floors.
> 
> The followings are the way I confirmed:
> 
> 1. Open LIightAndShadowBakedLight scene.
> 2. Change the shader of SceneElements material to HDRP/Toon.
> 3. Change the 1st shade map color to black or something like that.
> 
> Will you please try like above?
> 
> ![image](https://user-images.githubusercontent.com/4477357/129723926-f77a684d-97b1-4b6e-8418-75d67c6f70a2.png)

Hey there,
Yes I'm using the version from https://github.com/Unity-Technologies/com.unity.toonshader. I tried the scene you mentioned and the material settings. The problem is with additional lights, such as Spot or Point. As you can see here : 
![SpotLight](https://user-images.githubusercontent.com/4999276/129915907-b2954f39-5f6a-4ac9-920f-7441040c6855.png)
This is the same floor with a Directonal Light. 
![DirectionalLight](https://user-images.githubusercontent.com/4999276/129916069-bc2ffdbc-8ac5-45b2-9317-a9ba98c16e26.png)
The shadow looks like yours and works correctly. Looking at the shader code the shadows from additional lights are not taken into the final color. This is a shadow from the Spot Light when the material of the floor is set to the default HDRP/Lit
![SpotLight Shadow](https://user-images.githubusercontent.com/4999276/129916261-93645b3b-47c1-4858-b555-75e2e8c0c64d.png)
I also tried Deferred and Forward rendering it made no difference.

**Comment by H3idi-X** [comment]
Hi, As far as I see, we haven't supported those kind of future since legacy pipeline UTS.
I mean spot and point light **shadows** have not been supported. What you want to say is we should add those kind of features especially for HDRP?

**Comment by Kulgann** [comment]
> Hi, As far as I see, we haven't supported those kind of future since legacy pipeline UTS.
> I mean spot and point light **shadows** have not been supported. What you want to say is we should add those kind of features especially for HDRP?

Well yes,
We are currently producing a Anime style cinematic with HDRP and Point and Spot shadows will greatly improve the atmosphere.  Is it possible you can give me a ETA on supporting them or should I try and add them myself?

**Comment by H3idi-X** [comment]
We are currently working on affinity and controllability with HDRP features, such as high intensity light environment, SRP Batcher and so on. However, at least for now, we would not be able to  give high priority for those features you want as we are in a phase to  focus on stability and  more basic features.

**Comment by Kulgann** [comment]
> We are currently working on affinity and controllability with HDRP features, such as high intensity light environment, SRP Batcher and so on. However, at least for now, we would not be able to give high priority for those features you want as we are in a phase to focus on stability and more basic features.

Hey there, I implemented punctual shadowing for Spot and Point lights 
![final_shadows](https://user-images.githubusercontent.com/4999276/130222381-7ee3f0e7-3d95-42bf-a4d9-778061852a67.png)
Would you like me to create a pull request ?

**Comment by H3idi-X** [comment]
We appreciate your offer, but we would not be be able to accept it. We have other features that we need to focus on, such as integration with other unreleased module. Therefore, we are not able to give high priority to your proposed features maintenance.
If there are a lot of requests, We believe that we should add functions not only to HDRP but also to Legacy and URP. In that case, one rendering pipeline alone would not be adequate, and we would start with Legacy rather than HDRP.

**Comment by H3idi-X** [comment]
I forgot to say some.
Basically, UTS is a shader for characters, so we don't believe that kind of feature would be necessarily important and there is little possibility we  add all the features other shaders have.
