### ISSUE TITLE
Shader is shading certain angles black

### ISSUE THREAD

**Issue by LordChunder** [unity3d-jp/UnityChanToonShaderVer2_Project#90]
Hi there, I am not an expert in shader script. I have been trying for days to figure out how to get rid of the dark sides in my terrain. Please if anyone can point me in the right direction that would be much help. I feel like this is an easy solve. 

![](https://cdn.discordapp.com/attachments/493511507192184882/886934559281778698/unknown.png)

**Comment by H3idi-X** [comment]
Hi, If you just want to lighten dark side, putting one more light would be the most simple solution. I believe.

**Comment by H3idi-X** [comment]
How was the result? Do you have more questions? If not, I am going to close this. You can reopen the issue when we have more questions.

**Comment by LordChunder** [comment]
Yes it was solved thank you! Side note, can we expect to see a shader graph release???

**Comment by H3idi-X** [comment]
It is in planning yet as we need to focus on some other basic features such as how to support casting more than two directional light shadows  in URP and HDRP, How to adjust UTS light in HDRP high intensive light environment and so on.
If you have questions not related to your first question, please open another issue.
