### ISSUE TITLE
Object outlines stay on screen for a few seconds even if the camera isn't viewing the object

### ISSUE THREAD

**Issue by IzzyDev05** [unity3d-jp/UnityChanToonShaderVer2_Project#94]
I added outlines to my game objects, but now when I go and play the game (And even in the scene view, as shown in the video), the object outlines don't stick to the objects, but rather move with the camera, creating a rather unpleasant effect. I'm not really sure how to describe it, so I'm attaching a video clip of what I'm talking about. 
If there is anything else I should share, please do let me know and I'll do so. Thanks for the help!

https://user-images.githubusercontent.com/66153582/134153031-68f33ae8-774e-46fc-9707-a291b4e7f046.mp4

**Comment by H3idi-X** [comment]
HI, Will you please put more detailed information?

First of all, what does it mean “added outline to your gameObject”?
You use UTS and enabled outline or you applied our outline code to your original shader?

If you use UTS, how about the following?

- Render Pipeline Legacy, URP, HDRP.
- UTS Version 2.0.7.5, 2.0.8, Univerasl 2.x or Unity Toon Shader?

I see you use Windows and DX11.
I haven’t seen that phenomenon and I have no idea so far.

**Comment by IzzyDev05** [comment]
I'm using the "Universal render pipeline > Toon" shader in URP, and the version is 2.0.0. The issue was resolved when I unchecked HDR, so I'm not really sure what was going wrong. Since the issue is fixed now, should I close this issue?

**Comment by H3idi-X** [comment]
Thanks for giving tips. I'm not sure what was wrong too.
Yes, will you please close this issue as you have found the solution?

**Comment by IzzyDev05** [comment]
Sure thing! Thanks for the help!
