### ISSUE TITLE
I want to apply more than one BaseMap in UniversalToon.shader

### ISSUE THREAD

**Issue by kumi0708** [unity3d-jp/UnityChanToonShaderVer2_Project#99]
Hello
UTS/Universal 2.3.0
I am using https://github.com/unity3d-jp/UnityChanToonShaderVer2_Project/releases/tag/urp-2.3.0
I'm using
I want to apply more than one BaseMap in UniversalToon.shader, but I can't find a place to set them.
Is this possible?

Is there another way to set them?
Is there another way to set them? If not, are there plans to do so in the future?

**Comment by H3idi-X** [comment]
Hi, Thanks for reaching to us.

Unfortunately, no plans so far.
Will you please explain why it is necessary to you and how to use it if it doesn't make too much trouble?

**Comment by kumi0708** [comment]
Thanks for the reply.

The examples I want to do are
UV 1 → pattern (tiling)
UV 2 -> Lines drawn with texture

I would like to achieve the following

**Comment by H3idi-X** [comment]
In that case, pattern and line textures should be synthesized inside shader?
And its synthesizing logic must be able to customize. I don't believe just supporting additional base map satisfy your requests. Those kind of thing should be done shader graph or some other tools. We, however, haven't come to the point to support shader graph yet.

**Comment by H3idi-X** [comment]
No plans to add another BaseMap.
